---
- name: Installing and Launch Metricbeat
  hosts: webservers
  become: yes
  tasks:
    # Use command module
  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.16.1-amd64.deb

    # Use command module
  - name: Install filebeat .deb
    command: dpkg -i metricbeat-7.16.1-amd64.deb

    # Use copy module
  - name: Drop in install-metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/filebeat/install-metricbeat.yml

    # Use command module
  - name: Enable and Configure System Module
    command: metricbeat modules enable apache mysql

    # Use command module
  - name: Setup metricbeat
    command: metricbeat setup -e

    # Use command module
  - name: Start filebeat service
    command: service metricbeat start

    # Use systemd module
  - name: Enable service filebeat on boot
    systemd:
      name: metricbeat
      enabled: yes

